#pragma once

// STORES SOME HARDCODED LEVEL GEOMETRY TO USE ON RANDOM 
// NOT REALLY IDEAL BUT IT WORKS FOR AVOIDING A MORE COMPLEX LEVEL STORAGE/CONTENT LOADING SYSTEM

#include "s_tilemap.h"

// HARDCODED SINGLE LEVEL FOR NOW FOR THE SAKE OF TIME

#define LEVEL_GEOMETRY_OPTION_COUNT 1

extern tile level_geometry_options[LEVEL_GEOMETRY_OPTION_COUNT][LEVELS_HEIGHT][LEVELS_WIDTH];

void init_level_geometry();
void load_level_into_2d_array(int geometry, tile arr[LEVELS_HEIGHT][LEVELS_WIDTH]);